#!/usr/bin/env ruby
# coding: utf-8

require "researchmap2bib"
require 'thor'

class CLI < Thor
  option 'newline', :type => :boolean
  desc "generate ZIP_FILE", "researchmapの業績からbibliographyを作成"
  def generate(file_name)
    @s = Researchmap2bib::ResearchmapReader.new
    entries = @s.read_researchmap(file_name)

    results = Array.new
    entries.each do |entry|
      results.push(@s.write_bibliography_entry(entry))
    end

    puts options['newline'] == false ? results : results.join("\n")
  end

  desc "version", "バージョンを表示"
  def version
    puts "researchmap2bib version #{::Researchmap2bib::VERSION}"
  end
end

CLI.start(ARGV)
