#!/usr/bin/env ruby

require "researchmap2bib"

@s = Researchmap2bib::ResearchmapReader.new
entries = @s.read_researchmap('test/ychubachi.zip')

results = Array.new
entries.each do |entry|
  results.push(@s.write_bibliography_entry(entry))
end

puts results.join("\n")
